spring:
  application:
    name: leasing-schema
  profiles:
    active: dev
  data:
    mongodb:
      authentication-database: test
      username: my_user
      password: password123
      port: 27017
      host: localhost
      database: test
